### ISSUE TITLE
ReflectionException: Class braintree does not exist

### ISSUE THREAD

**Issue by HexagonStorms** [faustbrian/Laravel-Braintree#10]
Hello, 

First of all, thank you for creating this package. 

I ran ```composer require faustbrian/laravel-braintree``` and confirmed it is installed correctly. 
I ran ```php artisan vendor:publish --provider="BrianFaust\Braintree\BraintreeServiceProvider``` and setup up my sandbox keys inside of `config/braintree.php` as well. 

I'm trying to call this package from my controller, so I inserted ```use BrianFaust\Braintree\Facades\Braintree;``` at the top, and I'm just trying to generate a client token:

```Braintree::generate();```

I get the following error: "ReflectionException: Class braintree does not exist..."

I am pretty new to Laravel 5.4, so I get that this is probably just a namespace issue. But I can't seem to figure it out. I tried adding the following line to `config/app.php` 

```Braintree' => BrianFaust\Braintree\Facades\Braintree::class```

But no luck... I feel like this should be a super easy solution. Thank you in advance!
<img width="337" alt="2017-08-01_1437" src="https://user-images.githubusercontent.com/7490582/28843500-079744f0-76c7-11e7-86d4-9bce40df3eaa.png">

p.s. I also tried running `composer update` and then `composer dump auto-load` but no luck.

**Comment by faustbrian** [comment]
Have you registered the service provider in your config/app.php?
